import * as github from '@actions/github';
import { ReleaseNotesOutput } from '../types';
import { logger } from '../utils/logger';

export const PR_COMMENT_MARKER = '<!-- apple-connect-ai-deliver-pr-comment -->';

export function getLocaleFlag(locale: string): string {
  const map: Record<string, string> = {
    'en-US': '🇺🇸',
    'en-GB': '🇬🇧',
    'tr': '🇹🇷',
    'tr-TR': '🇹🇷',
    'de-DE': '🇩🇪',
    'fr-FR': '🇫🇷',
    'es-ES': '🇪🇸',
    'it': '🇮🇹',
    'ja': '🇯🇵',
    'ko': '🇰🇷',
    'pt-BR': '🇧🇷',
    'ru': '🇷🇺',
    'zh-Hans': '🇨🇳',
    'zh-Hant': '🇹🇼'
  };
  return map[locale] || '🌐';
}

export function formatPRComment(options: {
  releaseNotes: ReleaseNotesOutput;
  version: string;
  provider: string;
  model?: string;
  status: string;
}): string {
  const { releaseNotes, version, provider, model, status } = options;

  let body = `${PR_COMMENT_MARKER}\n`;
  body += `## 🍎 App Store "What's New" Preview\n\n`;
  body += `> 🤖 **Generated with:** \`${provider}${model ? ` (${model})` : ''}\` &bull; **Target Version:** \`${version || 'Next Release'}\` &bull; **Mode:** \`${status}\`\n\n`;
  body += `Here is how the release notes will look in App Store Connect when this Pull Request is merged:\n\n`;

  const locales = Object.keys(releaseNotes);
  locales.forEach((locale, index) => {
    const flag = getLocaleFlag(locale);
    const content = releaseNotes[locale];
    // First locale opened by default, others collapsible
    const isOpen = index === 0 ? ' open' : '';
    body += `<details${isOpen}>\n<summary><b>${flag} ${locale}</b></summary>\n\n\`\`\`text\n${content}\n\`\`\`\n\n</details>\n\n`;
  });

  body += `---\n*Automated preview generated by [Apple Connect AI Deliver](https://github.com/blgymtr/apple-connect-ai-deliver)*\n`;
  return body;
}

export async function upsertPRComment(
  token: string,
  options: {
    releaseNotes: ReleaseNotesOutput;
    version: string;
    provider: string;
    model?: string;
    status: string;
  }
): Promise<void> {
  const context = github.context;
  const prNumber = context.payload.pull_request?.number;

  if (!prNumber) {
    logger.info('Not running in a Pull Request context. Skipping PR comment.');
    return;
  }

  const octokit = github.getOctokit(token);
  const commentBody = formatPRComment(options);

  logger.info(`Fetching comments for Pull Request #${prNumber}...`);

  const { data: comments } = await octokit.rest.issues.listComments({
    ...context.repo,
    issue_number: prNumber
  });

  const existingComment = comments.find(c => c.body && c.body.includes(PR_COMMENT_MARKER));

  if (existingComment) {
    logger.info(`Updating existing preview comment (ID: ${existingComment.id}) on PR #${prNumber}...`);
    await octokit.rest.issues.updateComment({
      ...context.repo,
      comment_id: existingComment.id,
      body: commentBody
    });
    logger.success(`Successfully updated PR #${prNumber} comment.`);
  } else {
    logger.info(`Posting new preview comment to PR #${prNumber}...`);
    await octokit.rest.issues.createComment({
      ...context.repo,
      issue_number: prNumber,
      body: commentBody
    });
    logger.success(`Successfully posted preview comment to PR #${prNumber}.`);
  }
}
